services:
  flask:
    build: .
    ports:
      - "8000"
    # networks:
    #   - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    # networks:
    #   - mynetwork
    depends_on:
      - flask

# networks:
#   mynetwork:
#     driver: bridge
